const chevroletOnix = require("../src/assets/img/cars/chevrolet-onix-2022.webp");
const hyundaiGrand22 = require("../src/assets/img/cars/hyundai-grand-1-10-2022.webp");
const hyundaiGrand19 = require("../src/assets/img/cars/hyundai-grandi10-2019.webp");
const susukiAlto = require("../src/assets/img/cars/susuki-alto-2022.webp");
const susukiBaleno = require("../src/assets/img/cars/susuki-baleno-gls-2022.webp");
const susukiSpresso = require("../src/assets/img/cars/susuki-spresso-glx-2021.webp");
const toyotaRaize = require("../src/assets/img/cars/toyota-raize-2022.webp");

exports.dataCars = [
  {
    id: 1,
    photos: [hyundaiGrand22],
    name: "Hyundai Grand I10 2022",
    year: 2022,
    brand: "Hyundai",
    model: "Grand-i10",
    version: "VALUE",
    owners: 1,
    price: 13990000,
    mileage: 8900,
    fuel: "Bencina",
    transmission: "Manual",
    seats: 5,
    doors: 5,
    type: "Sedan",
    keys: 1,
  },
  {
    id: 2,
    photos: [susukiSpresso],
    name: "Suzuki S-Presso GLX 2021",
    year: 2021,
    brand: "Susuki",
    model: "S-Presso",
    version: "GLX",
    owners: 1,
    price: 9790000,
    mileage: 6700,
    fuel: "Bencina",
    transmission: "Manual",
    seats: 5,
    doors: 5,
    type: "Citycar",
    keys: 1,
  },
  {
    id: 3,
    photos: [susukiAlto],
    name: "Suzuki Alto 2022",
    year: 2022,
    brand: "Susuki",
    model: "Alto",
    version: "DLX",
    owners: 1,
    price: 6990000,
    mileage: 38400,
    fuel: "Bencina",
    transmission: "Manual",
    seats: 5,
    doors: 5,
    type: "Citycar",
    keys: 2,
  },
  {
    id: 4,
    photos: [hyundaiGrand19],
    name: "Hyundai Grand I10 2019",
    year: 2019,
    brand: "Hyundai",
    model: "Grand-i10",
    version: "VALUE",
    owners: 2,
    price: 12990000,
    mileage: 18500,
    fuel: "Bencina",
    transmission: "Manual",
    seats: 5,
    doors: 5,
    type: "Sedan",
    keys: 2,
  },
  {
    id: 5,
    photos: [susukiBaleno],
    name: "Suzuki GLS Baleno 2022",
    year: 2022,
    brand: "Susuki",
    model: "Baleno",
    version: "GLS",
    owners: 1,
    price: 12990000,
    mileage: 6900,
    fuel: "Bencina",
    transmission: "Manual",
    seats: 5,
    doors: 5,
    type: "Hatchback",
    keys: 2,
  },
  {
    id: 6,
    photos: [toyotaRaize],
    name: "Toyota Raize 2022",
    year: 2022,
    brand: "Toyota",
    model: "Raize",
    version: "CVT",
    owners: 1,
    price: 14490000,
    mileage: 7200,
    fuel: "Bencina",
    transmission: "Manual",
    seats: 5,
    doors: 5,
    type: "Suv",
    keys: 2,
  },
  {
    id: 7,
    photos: [chevroletOnix],
    name: "Chevrolet Onix RS 2022",
    year: 2022,
    brand: "Chevrolet",
    model: "Onix",
    version: "RS",
    owners: 1,
    price: 12990000,
    mileage: 9300,
    fuel: "Bencina",
    transmission: "Manual",
    seats: 5,
    doors: 5,
    type: "Hatchback",
    keys: 2,
  },
];
