exports.dataCars = [
  {
    id: 1,
    name: "HYUNDAI GRAND I10 2022",
    year: 2022,
    brand: "Hyundai",
    model: "Grand-i10",
    version: "VALUE",
    owners: 1,
    price: 13990000,
    mileage: 8900,
    fuel: "Bencina",
    transmission: "Manual",
    seats: 5,
    doors: 5,
    type: "Sedan",
    keys: 1,
  },
  {
    id: 2,
    name: "SUZUKI S-PRESSO GLX 2021",
    year: 2021,
    brand: "Susuki",
    model: "S-Presso",
    version: "GLX",
    owners: 1,
    price: 9790000,
    mileage: 6700,
    fuel: "Bencina",
    transmission: "Manual",
    seats: 5,
    doors: 5,
    type: "Citycar",
    keys: 1,
  },
  {
    id: 3,
    name: "SUZUKI ALTO 2022",
    year: 2022,
    brand: "Susuki",
    model: "Alto",
    version: "DLX",
    owners: 1,
    price: 6990000,
    mileage: 38400,
    fuel: "Bencina",
    transmission: "Manual",
    seats: 5,
    doors: 5,
    type: "Citycar",
    keys: 2,
  },
  {
    id: 4,
    name: "HYUNDAI GRAND I10 2019",
    year: 2019,
    brand: "Hyundai",
    model: "Grand-i10",
    version: "VALUE",
    owners: 2,
    price: 12990000,
    mileage: 18500,
    fuel: "Bencina",
    transmission: "Manual",
    seats: 5,
    doors: 5,
    type: "Sedan",
    keys: 2,
  },
  {
    id: 5,
    name: "SUZUKI GLS BALENO 2022",
    year: 2022,
    brand: "Susuki",
    model: "Baleno",
    version: "GLS",
    owners: 1,
    price: 12990000,
    mileage: 6900,
    fuel: "Bencina",
    transmission: "Manual",
    seats: 5,
    doors: 5,
    type: "Hatchback",
    keys: 2,
  },
  {
    id: 6,
    name: "TOYOTA RAIZE 2022",
    year: 2022,
    brand: "Toyota",
    model: "Raize",
    version: "CVT",
    owners: 1,
    price: 14490000,
    mileage: 7200,
    fuel: "Bencina",
    transmission: "Manual",
    seats: 5,
    doors: 5,
    type: "Suv",
    keys: 2,
  },
  {
    id: 7,
    name: "CHEVROLET ONIX RS 2022",
    year: 2022,
    brand: "Chevrolet",
    model: "Onix",
    version: "RS",
    owners: 1,
    price: 12990000,
    mileage: 9300,
    fuel: "Bencina",
    transmission: "Manual",
    seats: 5,
    doors: 5,
    type: "Hatchback",
    keys: 2,
  },
];
