const chevroletOnix = require("../src/assets/img/cars/chevrolet-onix-2022.webp");
const hyundaiGrand22 = require("../src/assets/img/cars/hyundai-grand-1-10-2022.webp");
const hyundaiGrand19 = require("../src/assets/img/cars/hyundai-grandi10-2019.webp");
const susukiAlto = require("../src/assets/img/cars/susuki-alto-2022.webp");
const susukiBaleno = require("../src/assets/img/cars/susuki-baleno-gls-2022.webp");
const susukiSpresso = require("../src/assets/img/cars/susuki-spresso-glx-2021.webp");
const toyotaRaize = require("../src/assets/img/cars/toyota-raize-2022.webp");

exports.dataCars = [
  {
    id: 1,
    photos: [hyundaiGrand22],
    name: "Chery Tiggo 2",
    year: 2019,
    brand: "Chery",
    model: "Tiggo 2",
    version: "GLS 1.5 MT",
    owners: 1,
    price: 9980000,
    mileage: 48000,
    fuel: "Bencina",
    transmission: "Manual",
    seats: 5,
    doors: 5,
    type: "suv",
    keys: 2,
  },
  {
    id: 2,
    photos: [susukiSpresso],
    name: "Hyundai Accent GL 2018",
    year: 2018,
    brand: "Hyundai",
    model: "Accent",
    version: "RB GL AC 6MT",
    owners: 2,
    price: 10990000,
    mileage: 47000,
    fuel: "Bencina",
    transmission: "Manual",
    seats: 5,
    doors: 4,
    type: "Sedan",
    keys: 2,
  },
  {
    id: 3,
    photos: [susukiAlto],
    name: "Nissan Versa Sense 1.6 MT 2021",
    year: 2021,
    brand: "Nissan",
    model: "Versa",
    version: "Sense 1.6 MT",
    owners: 1,
    price: 12990000,
    mileage: 35000,
    fuel: "Bencina",
    transmission: "Manual",
    seats: 5,
    doors: 4,
    type: "Sedan",
    keys: 2,
  },
  {
    id: 4,
    photos: [hyundaiGrand19],
    name: "Kia Sportage QL 2.0 AUT 2021",
    year: 2021,
    brand: "Kia",
    model: "Sportage",
    version: "QL 2.0",
    owners: 1,
    price: 19990000,
    mileage: 13000,
    fuel: "Bencina",
    transmission: "Automático",
    seats: 5,
    doors: 5,
    type: "suv",
    keys: 2,
  },
  {
    id: 5,
    photos: [susukiBaleno],
    name: "Toyota Yaris GLI E CVT 2023",
    year: 2023,
    brand: "Toyota",
    model: "Yaris",
    version: "GLI E 1.5 CVT",
    owners: 1,
    price: 14990000,
    mileage: 0,
    fuel: "Bencina",
    transmission: "Manual",
    seats: 5,
    doors: 4,
    type: "Sedan",
    keys: 2,
  },
  {
    id: 6,
    photos: [toyotaRaize],
    name: "Renault Koleos 2.5 AT 2014",
    year: 2014,
    brand: "Renault",
    model: "Koleos",
    version: "2.5 AT",
    owners: 1,
    price: 10990000,
    mileage: 113000,
    fuel: "Bencina",
    transmission: "Automático",
    seats: 5,
    doors: 5,
    type: "Suv",
    keys: 2,
  },
  {
    id: 7,
    photos: [chevroletOnix],
    name: "Toyota Yaris GLI E MT 2022",
    year: 2022,
    brand: "Toyota",
    model: "Yaris",
    version: "GLI E 1.5 MT",
    owners: 1,
    price: 14490000,
    mileage: 7000,
    fuel: "Bencina",
    transmission: "Manual",
    seats: 5,
    doors: 4,
    type: "Sedan",
    keys: 2,
  },
  {
    id: 8,
    photos: [chevroletOnix],
    name: "Toyota Yaris Sport 1.5 AT",
    year: 2014,
    brand: "Toyota",
    model: "Yaris",
    version: "SPORT 1.5 AT",
    owners: 3,
    price: 9890000,
    mileage: 81000,
    fuel: "Bencina",
    transmission: "Automático",
    seats: 5,
    doors: 5,
    type: "hb",
    keys: 1,
  },
];
