exports.cars = [
  {
    name: "HYUNDAI GRAND I10 2022",
    year: "2022",
    brand: "Hyundai",
    model: "Grand-i10",
    version: "VALUE",
    owners: 1,
    price: "$ 13.990.000",
    mileage: "8.900 km",
    fuel: "Bencina",
    transmission: "Manual",
    seats: "5",
    doors: "5",
    type: "Sedan",
    keys: 1,
  },
  {
    name: "SUZUKI S-PRESSO GLX 2021",
    year: "2021",
    brand: "Susuki",
    model: "S-Presso",
    version: "GLX",
    owners: 1,
    price: "$ 9.790.000",
    mileage: "6.700 km",
    fuel: "Bencina",
    transmission: "Manual",
    seats: "5",
    doors: "5",
    type: "Citycar",
    keys: 1,
  },
  {
    name: "SUZUKI ALTO 2022",
    year: "2022",
    brand: "Susuki",
    model: "Alto",
    version: "DLX",
    owners: 1,
    price: "$ 6.990.000",
    mileage: "38.400 km",
    fuel: "Bencina",
    transmission: "Manual",
    seats: "5",
    doors: "5",
    type: "Citycar",
    keys: 2,
  },
  {
    name: "HYUNDAI GRAND I10 2019",
    year: "2019",
    brand: "Hyundai",
    model: "Grand-i10",
    version: "VALUE",
    owners: 2,
    price: "$ 12.990.000",
    mileage: "18.500 km",
    fuel: "Bencina",
    transmission: "Manual",
    seats: "5",
    doors: "5",
    type: "Sedan",
    keys: 2,
  },
  {
    name: "SUZUKI GLS BALENO 2022",
    year: "2022",
    brand: "Susuki",
    model: "Baleno",
    version: "GLS",
    owners: 1,
    price: "$ 12.990.000",
    mileage: "6.900 km",
    fuel: "Bencina",
    transmission: "Manual",
    seats: "5",
    doors: "5",
    type: "Hatchback",
    keys: 2,
  },
  {
    name: "TOYOTA RAIZE 2022",
    year: "2022",
    brand: "Toyota",
    model: "Raize",
    version: "CVT",
    owners: 1,
    price: "$ 14.490.000",
    mileage: "7.200 km",
    fuel: "Bencina",
    transmission: "Manual",
    seats: "5",
    doors: "5",
    type: "Suv",
    keys: 2,
  },
  {
    name: "CHEVROLET ONIX RS 2022",
    year: "2022",
    brand: "Chevrolet",
    model: "Onix",
    version: "RS",
    owners: 1,
    price: "$ 12.990.000",
    mileage: "9.300 km",
    fuel: "Bencina",
    transmission: "Manual",
    seats: "5",
    doors: "5",
    type: "Hatchback",
    keys: 2,
  },
];
